/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TodoList {
      
    export type TodoStruct = {id: BigNumberish, owner: AddressLike, title: string, description: string, status: BigNumberish, createdAt: BigNumberish, updatedAt: BigNumberish, exists: boolean}

    export type TodoStructOutput = [id: bigint, owner: string, title: string, description: string, status: bigint, createdAt: bigint, updatedAt: bigint, exists: boolean] & {id: bigint, owner: string, title: string, description: string, status: bigint, createdAt: bigint, updatedAt: bigint, exists: boolean }
  
    }

  export interface TodoListInterface extends Interface {
    getFunction(nameOrSignature: "createTodo" | "deleteTodo" | "getAllTodos" | "getAllTodosPaginated" | "getMyTodo" | "getMyTodos" | "getTodoById" | "getTodosOf" | "totalTodos" | "updateStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TodoCreated" | "TodoDeleted" | "TodoStatusUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'createTodo', values: [string, string]): string;
encodeFunctionData(functionFragment: 'deleteTodo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllTodos', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllTodosPaginated', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMyTodo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMyTodos', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTodoById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTodosOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalTodos', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateStatus', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createTodo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deleteTodo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllTodos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllTodosPaginated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMyTodo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMyTodos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTodoById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTodosOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTodos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateStatus', data: BytesLike): Result;
  }

  
    export namespace TodoCreatedEvent {
      export type InputTuple = [id: BigNumberish, owner: AddressLike, title: string, createdAt: BigNumberish];
      export type OutputTuple = [id: bigint, owner: string, title: string, createdAt: bigint];
      export interface OutputObject {id: bigint, owner: string, title: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TodoDeletedEvent {
      export type InputTuple = [id: BigNumberish, owner: AddressLike, deletedAt: BigNumberish];
      export type OutputTuple = [id: bigint, owner: string, deletedAt: bigint];
      export interface OutputObject {id: bigint, owner: string, deletedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TodoStatusUpdatedEvent {
      export type InputTuple = [id: BigNumberish, owner: AddressLike, oldStatus: BigNumberish, newStatus: BigNumberish, updatedAt: BigNumberish];
      export type OutputTuple = [id: bigint, owner: string, oldStatus: bigint, newStatus: bigint, updatedAt: bigint];
      export interface OutputObject {id: bigint, owner: string, oldStatus: bigint, newStatus: bigint, updatedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TodoList extends BaseContract {
    
    connect(runner?: ContractRunner | null): TodoList;
    waitForDeployment(): Promise<this>;

    interface: TodoListInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createTodo: TypedContractMethod<
      [title: string, description: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    deleteTodo: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAllTodos: TypedContractMethod<
      [],
      [TodoList.TodoStructOutput[]],
      'view'
    >
    

    
    getAllTodosPaginated: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[TodoList.TodoStructOutput[], bigint] & {todos: TodoList.TodoStructOutput[], total: bigint }],
      'view'
    >
    

    
    getMyTodo: TypedContractMethod<
      [id: BigNumberish, ],
      [TodoList.TodoStructOutput],
      'view'
    >
    

    
    getMyTodos: TypedContractMethod<
      [],
      [TodoList.TodoStructOutput[]],
      'view'
    >
    

    
    getTodoById: TypedContractMethod<
      [id: BigNumberish, ],
      [TodoList.TodoStructOutput],
      'view'
    >
    

    
    getTodosOf: TypedContractMethod<
      [user: AddressLike, ],
      [TodoList.TodoStructOutput[]],
      'view'
    >
    

    
    totalTodos: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateStatus: TypedContractMethod<
      [id: BigNumberish, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createTodo'): TypedContractMethod<
      [title: string, description: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deleteTodo'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAllTodos'): TypedContractMethod<
      [],
      [TodoList.TodoStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAllTodosPaginated'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[TodoList.TodoStructOutput[], bigint] & {todos: TodoList.TodoStructOutput[], total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getMyTodo'): TypedContractMethod<
      [id: BigNumberish, ],
      [TodoList.TodoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMyTodos'): TypedContractMethod<
      [],
      [TodoList.TodoStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTodoById'): TypedContractMethod<
      [id: BigNumberish, ],
      [TodoList.TodoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTodosOf'): TypedContractMethod<
      [user: AddressLike, ],
      [TodoList.TodoStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'totalTodos'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateStatus'): TypedContractMethod<
      [id: BigNumberish, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'TodoCreated'): TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
getEvent(key: 'TodoDeleted'): TypedContractEvent<TodoDeletedEvent.InputTuple, TodoDeletedEvent.OutputTuple, TodoDeletedEvent.OutputObject>;
getEvent(key: 'TodoStatusUpdated'): TypedContractEvent<TodoStatusUpdatedEvent.InputTuple, TodoStatusUpdatedEvent.OutputTuple, TodoStatusUpdatedEvent.OutputObject>;

    filters: {
      
      'TodoCreated(uint256,address,string,uint256)': TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
      TodoCreated: TypedContractEvent<TodoCreatedEvent.InputTuple, TodoCreatedEvent.OutputTuple, TodoCreatedEvent.OutputObject>;
    

      'TodoDeleted(uint256,address,uint256)': TypedContractEvent<TodoDeletedEvent.InputTuple, TodoDeletedEvent.OutputTuple, TodoDeletedEvent.OutputObject>;
      TodoDeleted: TypedContractEvent<TodoDeletedEvent.InputTuple, TodoDeletedEvent.OutputTuple, TodoDeletedEvent.OutputObject>;
    

      'TodoStatusUpdated(uint256,address,uint8,uint8,uint256)': TypedContractEvent<TodoStatusUpdatedEvent.InputTuple, TodoStatusUpdatedEvent.OutputTuple, TodoStatusUpdatedEvent.OutputObject>;
      TodoStatusUpdated: TypedContractEvent<TodoStatusUpdatedEvent.InputTuple, TodoStatusUpdatedEvent.OutputTuple, TodoStatusUpdatedEvent.OutputObject>;
    
    };
  }